name: Build

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        illuminate-version:
          - 9
          - 10
          - 11
          - 12
        php-version:
          - 8.0
          - 8.1
          - 8.2
          - 8.3
          - 8.4
        exclude:
          - illuminate-version: 10
            php-version: 8.0
          - illuminate-version: 11
            php-version: 8.0
          - illuminate-version: 11
            php-version: 8.1
          - illuminate-version: 12
            php-version: 8.0
          - illuminate-version: 12
            php-version: 8.1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require \
            --no-ansi \
            --no-interaction \
            --no-progress \
            --no-scripts \
            --prefer-dist \
            illuminate/support:^${{ matrix.illuminate-version }}

      - name: Lint Code
        run: composer lint

      - name: Run tests
        run: composer test
